### PR TITLE
Sue Lynn's blog post

### PR DESCRIPTION
**Pull request by suelynnmah**

### CODE REVIEW

**Comment by suelynnmah** [comment]
@patrickabolger

**Review by patrickabolger — COMMENTED** [review]
@suelynnmah This looks good to me. We should come up with a more personal photo of you though.

**Comment by suelynnmah** [comment]
@patrickabolger Is this picture okay?

**Comment by patrickabolger** [comment]
@suelynnmah Sorry. I just saw this. Can you crop this so that it's just you? You wouldn't want people thinking that you were Becca, or vice-versa.

**Comment by suelynnmah** [comment]
@patrickabolger done :)

**Pull request merged**
